// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1fzbHDkdlv5SRGMYD1D4FFbGpVWEFAho',
    appId: '1:576901470679:web:44f74e1e0cde67db349392',
    messagingSenderId: '576901470679',
    projectId: 'todo-app-4c93c',
    authDomain: 'todo-app-4c93c.firebaseapp.com',
    storageBucket: 'todo-app-4c93c.firebasestorage.app',
    measurementId: 'G-5HV34L6MDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Aqi2mgKbO-pmGiYTFRCVKv_4zD4fa00',
    appId: '1:576901470679:android:af0d74e32ad84b04349392',
    messagingSenderId: '576901470679',
    projectId: 'todo-app-4c93c',
    storageBucket: 'todo-app-4c93c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcD1XDrI_zf8sU3QW3AOlCWBe8ueJptgY',
    appId: '1:576901470679:ios:b164efd0a1ea02eb349392',
    messagingSenderId: '576901470679',
    projectId: 'todo-app-4c93c',
    storageBucket: 'todo-app-4c93c.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcD1XDrI_zf8sU3QW3AOlCWBe8ueJptgY',
    appId: '1:576901470679:ios:b164efd0a1ea02eb349392',
    messagingSenderId: '576901470679',
    projectId: 'todo-app-4c93c',
    storageBucket: 'todo-app-4c93c.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSPBlNqjTdtevLr4IC5_A5INRZ_p7nfEY',
    appId: '1:230645514865:web:428506e2d2330031c711d0',
    messagingSenderId: '230645514865',
    projectId: 'todo-app-e37ca',
    authDomain: 'todo-app-e37ca.firebaseapp.com',
    storageBucket: 'todo-app-e37ca.firebasestorage.app',
    measurementId: 'G-NGW5H7L0CQ',
  );
}