// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSPBlNqjTdtevLr4IC5_A5INRZ_p7nfEY',
    appId: '1:230645514865:web:7091f67771bf39e8c711d0',
    messagingSenderId: '230645514865',
    projectId: 'todo-app-e37ca',
    authDomain: 'todo-app-e37ca.firebaseapp.com',
    storageBucket: 'todo-app-e37ca.firebasestorage.app',
    measurementId: 'G-F839WTNC9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZy-j3dxr2HWuxTo16QU2BfNofKZ_wtOQ',
    appId: '1:230645514865:android:8d51076560f0fbfec711d0',
    messagingSenderId: '230645514865',
    projectId: 'todo-app-e37ca',
    storageBucket: 'todo-app-e37ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcuPVHAkxpd9MLVmLDN7pFV0pHozkoz3s',
    appId: '1:230645514865:ios:fd23d8fd2dedccfcc711d0',
    messagingSenderId: '230645514865',
    projectId: 'todo-app-e37ca',
    storageBucket: 'todo-app-e37ca.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcuPVHAkxpd9MLVmLDN7pFV0pHozkoz3s',
    appId: '1:230645514865:ios:fd23d8fd2dedccfcc711d0',
    messagingSenderId: '230645514865',
    projectId: 'todo-app-e37ca',
    storageBucket: 'todo-app-e37ca.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSPBlNqjTdtevLr4IC5_A5INRZ_p7nfEY',
    appId: '1:230645514865:web:428506e2d2330031c711d0',
    messagingSenderId: '230645514865',
    projectId: 'todo-app-e37ca',
    authDomain: 'todo-app-e37ca.firebaseapp.com',
    storageBucket: 'todo-app-e37ca.firebasestorage.app',
    measurementId: 'G-NGW5H7L0CQ',
  );
}
